services:
    testingbot_eventlistener:
        class: TestingBot\ResultSubmitter\Listener\EventSubscriber
        tags:
            - { name: event_dispatcher.subscriber }
        arguments: [%testingbot.key%, %testingbot.secret%, @testingbot_httpclient]

    testingbot_httpclient:
        class: \GuzzleHttp\Client
        public: false
